name: Build and Run Spring Boot Docker Compose

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Spring Boot application With Tests
        run: |
          ./gradlew clean build

      - name: Run Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./postman-docker-compose.yml"
          action: "up"

      - name: Run Application With Postman Tests
        run: |
          docker compose -f postman-docker-compose.yml up --build --exit-code-from newman

      - name: Clean up containers
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./postman-docker-compose.yml"
          action: "down"
